name: Deploy OCI Instance Creator to Docker

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  dist:
    name: Build and Run Instance Creator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lowercase Repository Name
        run: echo "NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ env.NAME }}:latest

      - name: Create OCI Key File
        run: |
          mkdir -p keys
          echo "${{ secrets.OCI_KEY_FILE }}" > keys/oci.key
          chmod 600 keys/oci.key

      - name: Run OCI Instance Creator
        run: |
          docker run --rm \
            -v $(pwd)/keys/oci.key:/keys/oci.key \
            -e OCI_USER_ID="${{ secrets.OCI_USER_ID }}" \
            -e OCI_TENANCY_ID="${{ secrets.OCI_TENANCY_ID }}" \
            -e OCI_SUBNET_ID="${{ secrets.OCI_SUBNET_ID }}" \
            -e OCI_IMAGE_ID="${{ secrets.OCI_IMAGE_ID }}" \
            -e OCI_REGION="${{ secrets.OCI_REGION }}" \
            -e OCI_FINGERPRINT="${{ secrets.OCI_FINGERPRINT }}" \
            -e SSH_KEY="${{ secrets.SSH_KEY }}" \
            ghcr.io/${{ env.NAME }}:latest
