name: Deploy OCI Instance Creator to Docker

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  dist:
    name: Build and Run Instance Creator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lowercase Repository Name
        run: echo "NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ env.NAME }}:latest

      - name: Write OCI Private Key File
        run: |
          mkdir -p keys
          printf '%s' "${{ secrets.OCI_PRIVATE_KEY }}" | base64 --decode > keys/oci.key
          chmod 600 keys/oci.key

      - name: Check Key File Format
        run: head -n 1 keys/oci.key

      - name: Run OCI Instance Creator
        run: |
          docker run --rm \
            -v $(pwd)/keys/oci.key:/keys/oci.key \
            -e OCI_USER_ID="${{ secrets.OCI_USER_ID }}" \
            -e OCI_USER_OCID="${{ secrets.OCI_USER_OCID }}" \
            -e OCI_TENANCY_ID="${{ secrets.OCI_TENANCY_ID }}" \
            -e OCI_TENANCY_OCID="${{ secrets.OCI_TENANCY_OCID }}" \
            -e OCI_SUBNET_ID="${{ secrets.OCI_SUBNET_ID }}" \
            -e SUBNET_OCID="${{ secrets.SUBNET_OCID }}" \
            -e OCI_IMAGE_ID="${{ secrets.OCI_IMAGE_ID }}" \
            -e OCI_IMAGE_OCID="${{ secrets.OCI_IMAGE_OCID }}" \
            -e OCI_COMPARTMENT_OCID="${{ secrets.OCI_COMPARTMENT_OCID }}" \
            -e OCI_REGION="${{ secrets.OCI_REGION }}" \
            -e OCI_FINGERPRINT="${{ secrets.OCI_FINGERPRINT }}" \
            -e SSH_KEY="${{ secrets.SSH_KEY }}" \
            -e SSH_PUBLIC_KEY="${{ secrets.SSH_PUBLIC_KEY }}" \
            -e CPUS="${{ secrets.CPUS }}" \
            -e SHAPE="${{ secrets.SHAPE }}" \
            -e VOLUME_SIZE="${{ secrets.VOLUME_SIZE }}" \
            -e CREATE_INTERVAL_SECONDS="${{ secrets.CREATE_INTERVAL_SECONDS }}" \
            -e KEY_PATH="/keys/oci.key" \
            ghcr.io/${{ env.NAME }}:latest
